### ISSUE TITLE
Shouldn't use process.arch

### ISSUE THREAD

**Issue by simonepri** [kevva/os-filter-obj#1]
`process.arch` returns a string identifying the operating system CPU architecture for which the Node.js binary was compiled.
This is not the same as the operating system CPU architecture. For example, you can run Node.js 32-bit on a 64-bit OS. In that situation, `process.arch` will return a misleading 'x86' (32-bit) value, instead of 'x64' (64-bit).

We could use this package instead:
https://github.com/feross/arch

@kevva 
It's okay for you if I open a PR?

**Comment by kevva** [comment]
Sure, PR welcome :).

**Comment by simonepri** [comment]
@kevva maybe we can keep 2 options
`arch` will use the `arch package` for the comparison
`nodeArch` will use `process.arch`
What do you think?

Also I think that this could be considered a `breaking change` because it changes the behaviour of the filtering.

**Comment by kevva** [comment]
Nah, I don't see much use for it in this module.

> Also I think that this could be considered a `breaking change` because it changes the behaviour of the filtering.

Yes.

**Comment by simonepri** [comment]
See #2
